FrontOffice.MVC/Models/ErrorViewModel.cs
using System;

namespace FrontOffice.MVC.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

FrontOffice.MVC/Models/FetchDataModel.cs
namespace FrontOffice.MVC.Models
{
    public class FetchDataModel
    {
        public string Message { get; set; }
        public bool IsFetched { get; set; }
    }
}

FrontOffice.MVC/Controllers/BaseCategoryController.cs
using System.Threading.Tasks;
using BusinessLayer.Helpers;
using Microsoft.AspNetCore.Mvc;

namespace FrontOffice.MVC.Controllers
{
    public class BaseCategoryController : Controller
    {
        private readonly BaseCategoryHelper _baseCategoryHelper;

        public BaseCategoryController(BaseCategoryHelper baseCategoryHelper)
        {
            _baseCategoryHelper = baseCategoryHelper;
        }

        public async Task<IActionResult> Index()
        {
            return View(await  _baseCategoryHelper.GetAll());
        }
    }
}

FrontOffice.MVC/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using CommonLayer.ViewModels;
using ServiceLayer.Interfaces;

namespace FrontOffice.MVC.Controllers
{
    public class CategoryController : Controller
    {
        private readonly ICategoryService _categoryService;

        public CategoryController(ICategoryService categoryService)
        {
            _categoryService = categoryService;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _categoryService.GetAllCategories());
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Add(CategoryViewModel model)
        {
            await _categoryService.AddCategory(model);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            return View(await _categoryService.GetCategory(id));
        }

        [HttpPost]
        public async Task<IActionResult> Edit(CategoryViewModel model)
        {
            await _categoryService.EditCategory(model);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            await _categoryService.DeleteCategory(id);
            return RedirectToAction("Index");
        }
    }
}

FrontOffice.MVC/Controllers/FetchDataController.cs
    using System.Threading.Tasks;
using FrontOffice.MVC.Models;
using Microsoft.AspNetCore.Mvc;
using ServiceLayer.Interfaces;

namespace FrontOffice.MVC.Controllers
{
    public class FetchDataController : Controller
    {
        private readonly IFetchDataService _fetchDataService;

        public FetchDataController(IFetchDataService fetchDataService)
        {
            _fetchDataService = fetchDataService;
        }

        public IActionResult Index()
        {
            return View(new FetchDataModel());
        }
        
        [HttpPost]
        public async Task<IActionResult> FetchBaseCategories()
        {
            var result = await _fetchDataService.FetchBaseCategories();
            return View("Index", new FetchDataModel
            {
                IsFetched = true,
                Message = $"Successfully fetched {result} base categories"
            });
        }

        [HttpPost]
        public async Task<IActionResult> FetchCategories()
        {
            var result = await _fetchDataService.FetchCategories();
            return View("Index", new FetchDataModel
            {
                IsFetched = true,
                Message = $"Successfully fetched {result} categories"
            });
        }

        [HttpPost]
        public async Task<IActionResult> FetchProducts()
        {
            var result = await _fetchDataService.FetchProducts();
            return View("Index", new FetchDataModel
            {
                IsFetched = true,
                Message = $"Successfully fetched {result} products"
            });
        }
    }
}

FrontOffice.MVC/Controllers/HomeController.cs
using FrontOffice.MVC.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace FrontOffice.MVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

FrontOffice.MVC/Views/BaseCategory/Add.cshtml
@model CommonLayer.ViewModels.BaseCategoryViewModel

<div class="container">
    <div class="col-sm-6">
        <form method="post" asp-action="Add">
            <div class="form-group">
                <label asp-for="Name"></label>
                <input asp-for="Name" type="text" class="form-control" >
            </div>
            <div>
                <button class="btn btn-success" type="submit">Add category</button>
            </div>
        </form>
    </div>
</div>

FrontOffice.MVC/Views/BaseCategory/Edit.cshtml
@model CommonLayer.ViewModels.BaseCategoryViewModel

<div class="container">
    <div class="col-sm-6">
        <form method="post" asp-action="Edit">
            @Html.HiddenFor(x=>x.Id)
            <div class="form-group">
                <label asp-for="Name"></label>
                <input asp-for="Name" type="text" class="form-control" value="@Model.Name">
            </div>
            <div>
                <button class="btn btn-success" type="submit">Update category</button>
            </div>
        </form>
    </div>
</div>

FrontOffice.MVC/Views/BaseCategory/Index.cshtml
@using CommonLayer.ViewModels
@model List<BaseCategoryViewModel>

<div class="container">
    <h2>Base categories</h2>
    <table class="table table-bordered">
        <thead>
        <tr>
            <th>@nameof(BaseCategoryViewModel.Name)</th>
        </tr>
        </thead>
        <tbody>
        @if (Model == null || Model.Count < 1)
        {
            <tr>
                <td>No data</td>
            </tr>
        }
        else
        {
            foreach (var category in Model)
            {
                <tr>
                    <td>@category.Name</td>
                </tr>
            }
        }
        </tbody>
    </table>
</div>

FrontOffice.MVC/Views/Category/Add.cshtml
@model CommonLayer.ViewModels.CategoryViewModel

<div class="container">
    <div class="col-sm-6">
        <form method="post" asp-action="Add">
            <div class="form-group">
                <label asp-for="Name"></label>
                <input asp-for="Name" type="text" class="form-control" >
            </div>
            <div>
                <button class="btn btn-success" type="submit">Add category</button>
            </div>
        </form>
    </div>
</div>

FrontOffice.MVC/Views/Category/Edit.cshtml
@model CommonLayer.ViewModels.CategoryViewModel

<div class="container">
    <div class="col-sm-6">
        <form method="post" asp-action="Edit">
            @Html.HiddenFor(x=>x.Id)
            <div class="form-group">
                <label asp-for="Name"></label>
                <input asp-for="Name" type="text" class="form-control" value="@Model.Name">
            </div>
            <div>
                <button class="btn btn-success" type="submit">Update category</button>
            </div>
        </form>
    </div>
</div>

FrontOffice.MVC/Views/Category/Index.cshtml
@using CommonLayer.ViewModels
@model List<CategoryViewModel>

<div class="container">
    <h2>Categories</h2>
    <div class="row mb-2">
        <div class="col-sm-4 text-center">
            <a class="btn btn-primary btn-block" href="@Url.Action("Add")">Add new Category</a>
        </div>
    </div>
    <table class="table table-bordered">
        <thead>
        <tr>
            <th>@nameof(CategoryViewModel.Name)</th>
            <th>Edit</th>
            <th>Delete</th>
        </tr>
        </thead>
        <tbody>
        @if (Model == null || Model.Count < 1)
        {
            <tr>
                <td colspan="3">No data</td>
            </tr>
        }
        else
        {
            foreach (var category in Model)
            {
                <tr>
                    <td>@category.Name</td>
                    <td><a class="btn btn-warning btn-block" href="@Url.Action("Edit")?id=@category.Id"><i class="bi bi-file-earmark-binary-fill"></i></a></td>
                    <td><a class="btn btn-danger btn-block" href="@Url.Action("Delete")?id=@category.Id"><i class="bi bi-trash-fill"></i></a></td>
                </tr>
            }
        }
        </tbody>
    </table>
</div>
@section Scripts
{
    <script>
        window.addEventListener('DOMContentLoaded', (event) => {
            const menuItems = document.getElementById('header-menu').children;
            for (const item in menuItems) {
                console.log(menuItems[item]);
                if (menuItems[item].children != undefined)
                menuItems[item].classList.remove('active');
            }
            document.getElementById('nav-item-category').classList.add('active');
        });
    </script>
}

FrontOffice.MVC/Views/FetchData/Index.cshtml
@model FetchDataModel

<div class="container">
    <div class="row">
        <div class="col-sm-12 col-md-4">
            <form asp-controller="FetchData" asp-action="FetchBaseCategories" method="post">
                <button class="btn btn-primary m-2">Fetch Base Categories</button>
            </form>
        </div>

        <div class="col-sm-12 col-md-4">
            <form asp-controller="FetchData" asp-action="FetchCategories" method="post">
                <button class="btn btn-primary m-2">Fetch Categories</button>
            </form>
        </div>

        <div class="col-sm-12 col-md-4">
            <form asp-controller="FetchData" asp-action="FetchProducts" method="post">
                <button class="btn btn-primary m-2">Fetch Products</button>
            </form>
        </div>
    </div>

    @if(Model.IsFetched)
    {
        <div class="row">
            <p class="col-sm-12 alert alert-success">@Model.Message</p>
        </div>
    }
</div>

@section Scripts
{
    <script>
        window.addEventListener('DOMContentLoaded', (event) => {
            const menuItems = document.getElementById('header-menu').children;
            for (const item in menuItems) {
                console.log(menuItems[item]);
                if (menuItems[item].children != undefined)
                    menuItems[item].classList.remove('active');
            }
            document.getElementById('nav-item-api').classList.add('active');
        });
    </script>
}

FrontOffice.MVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

@section Scripts
{
    <script>
        window.addEventListener('DOMContentLoaded', (event) => {
            const menuItems = document.getElementById('header-menu').children;
            for (const item in menuItems) {
                console.log(menuItems[item]);
                if (menuItems[item].children != undefined)
                    menuItems[item].classList.remove('active');
            }
            document.getElementById('nav-item-home').classList.add('active');
        });
    </script>
}

FrontOffice.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FrontOffice.MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.0/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FrontOffice.MVC</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1" id="header-menu">
                        <li class="nav-item active" id="nav-item-home">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item" id="nav-item-category">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Index">Categories</a>
                        </li>
                        <li class="nav-item" id="nav-item-base-category">
                            <a class="nav-link text-dark" asp-area="" asp-controller="BaseCategory" asp-action="Index">Base Categories</a>
                        </li>
                        <li class="nav-item" id="nav-item-api">
                            <a class="nav-link text-dark" asp-area="" asp-controller="FetchData" asp-action="Index">Fetch API Data</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - FrontOffice.MVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>